Create Website Footer
acm-uic/sparkhacks-2023 pull request #168
Opened 2023-02-26 09:48 UTC by iomerkoyuncu

Hi, I'm İsmet, I want to help with this issue.

First of all, I added "flex flex-col justify-between h-screen" to layout div on line 6. To anchor the footer to the bottom of the page.

Navbar
Any Page / Content
Footer

2023-02-26 14:35 UTC, ChristianBingman commented
Please add a comment to this issu rso I can assign you #168

2023-02-28 16:27 UTC, ChristianBingman requested changes
Please remove the package-lock.json and just a couple changes for now.

2023-02-28 16:27 UTC, ChristianBingman commented on src/pages/layout.js
> +                    <p className='text-[12px]'>License is located on this sites Github Repo.</p>
Github Repo should be a link

2023-02-28 16:27 UTC, ChristianBingman commented on src/pages/layout.js
> +        <div className='flex flex-col justify-between h-screen'>
This styling shouldn't go over everything

2023-03-01 11:32 UTC, iomerkoyuncu commented
Hi again, I added link to github repo. Deleted package.json. Also removed the "h-screen" and other classes.

2023-03-01 11:43 UTC, iomerkoyuncu commented
The last commit is for more proper commit message. :)

2023-03-02 17:00 UTC, ChristianBingman commented
It looks like you deleted the whole package-lock.json file. You need to re-add the original back to the repo. You can do this with `git checkout main -- package-lock.json`

2023-03-04 03:21 UTC, ChristianBingman approved these changes
Does not properly wrap on mobile, but for time purposes I will go ahead and fix the rest. Thank you!

2023-03-04 03:23 UTC, merged